apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: server
  labels:
    app: server
spec: 
  selector:
    matchLabels:
      app: server
  replicas: 4
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: fabiocaettano74/servergo:v04      