---
- name: Install Kubectl
  hosts: droplet01
  gather_facts: true
  tasks:
    - name: Dowload
      shell: >
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - name: Install
      become: root
      shell: >
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    - name: Move Kubectl
      become: root
      shell: |
          chmod +x kubectl
          mkdir -p ~/.local/bin
          mv ./kubectl ~/.local/bin/kubectl