---
- name: Install Kind
  hosts: droplet01
  gather_facts: true
  tasks:
     - name: Download Binary
       shell: >
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
     - name: Move to folder bin
       become: root
       shell: |
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind