---
- name: Git Global
  hosts: droplet01
  gather_facts: True
  tasks:     
     - name: "Config Global List"
       shell: |
         git config --global user.email {{ git_email }}
         git config --global user.name {{ git_name }}
       args:
        chdir: /{{ git_folder }}